name: Scrape Job Listings

on:
  schedule:
    - cron: '*/600 * * * *'  # This runs every 600 minutes
  workflow_dispatch: 

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run scraper
        run: |
          python main.py
